/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote.interfaces;

/**
 *
 * @author Rocha
 */
public class JanelaPrivada extends javax.swing.JPanel {

    /**
     * Creates new form JanelaPrivada
     */
    public JanelaPrivada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReceberPrivado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaEnviarPrivado = new javax.swing.JTextArea();
        EnviarPrivado = new javax.swing.JButton();
        LimparPrivado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setAutoscrolls(true);

        txtAreaReceberPrivado.setEditable(false);
        txtAreaReceberPrivado.setColumns(20);
        txtAreaReceberPrivado.setLineWrap(true);
        txtAreaReceberPrivado.setRows(5);
        txtAreaReceberPrivado.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtAreaReceberPrivado);

        txtAreaEnviarPrivado.setColumns(20);
        txtAreaEnviarPrivado.setLineWrap(true);
        txtAreaEnviarPrivado.setRows(5);
        jScrollPane2.setViewportView(txtAreaEnviarPrivado);

        EnviarPrivado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/interfaces/imagens/accept.png"))); // NOI18N
        EnviarPrivado.setText("Enviar");
        EnviarPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarPrivadoActionPerformed(evt);
            }
        });

        LimparPrivado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/interfaces/imagens/newspaper.png"))); // NOI18N
        LimparPrivado.setText("Limpar");
        LimparPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparPrivadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 113, Short.MAX_VALUE)
                        .addComponent(LimparPrivado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnviarPrivado))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnviarPrivado)
                    .addComponent(LimparPrivado)))
        );

        jLabel1.setText("Conversa com:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarPrivadoActionPerformed
        // TODO add your handling code here:
        String texto = this.txtAreaEnviarPrivado.getText();
        if (!texto.isEmpty()) {
            String nome = this.mensagem.getNome();

            this.mensagem = new ChatMensagem();

            this.mensagem.setNome(nome);
            this.mensagem.setMensagem(texto);
            this.mensagem.setAction(Action.SEND_ALL);

            this.servico.send(this.mensagem);
        }

        this.txtAreaEnviarPrivado.setText("");
    }//GEN-LAST:event_EnviarPrivadoActionPerformed

    private void LimparPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparPrivadoActionPerformed
        // TODO add your handling code here:
        this.txtAreaReceberPrivado.setText("");
    }//GEN-LAST:event_LimparPrivadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarPrivado;
    private javax.swing.JButton LimparPrivado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaEnviarPrivado;
    private javax.swing.JTextArea txtAreaReceberPrivado;
    // End of variables declaration//GEN-END:variables
}
